---
- name: installing docker and running containers on test server
  hosts: all
  become: true
  connection: ssh
  tasks:
    - name: update instance
      apt:
        update_cache: yes
    - name: install docker
      apt:
        name: docker.io
        state: present

    - name: start docker
      service:
        name: docker
        state: started
          # - name: stop existed container
          # shell: docker stop $(docker ps -a -q)
          #become: yes
          # - name: delete all container
          #shell: docker rm $(docker ps -a -q)

    - name: create container
      command: sudo docker run -itd -p 8084:8081 moreaniket/insurance:1.0
